name: recombee_client
description: Recombee API Wrapper.
version: 1.2.0
homepage: https://github.com/F1dsy/recombee-client

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  http: ^1.2.2
  crypto: ^3.0.6

dev_dependencies:
  test: ^1.17.10
  lints: ^5.0.0
